### ISSUE TITLE
hook 

### ISSUE THREAD

**Issue by shimengmengya** [hunto/MasKD#3]
Hello, may I ask if your maskhook is added in the anaconda environment or in the maskd folder, and it always shows that the maskdhook is not in the hook registration module

**Comment by Gumpest** [comment]
Hi, our maskhook is added in the maskd folder, and we advise to install mmdet from source like:
`git clone https://github.com/open-mmlab/mmdetection.git`
`cd mmdetection`
`pip install -v -e .`
