### ISSUE TITLE
Could you provide the MMRazor Config file for segmentation distillation?

### ISSUE THREAD

**Issue by cape-zck** [hunto/MasKD#6]
Thank you for your outstanding work. I have seen the contents of the semantic segmentation folder, but I don’t seem to find the corresponding MMRazor semantic segmentation knowledge distillation config file. Could you provide it?

**Comment by hunto** [comment]
Hi @cape-zck ,

Our experiments on semantic segmentation were not conducted on MMRazor, as we need to keep the training strategies and settings the same as previous works. Our code is based on [CIRKD](https://github.com/winycg/CIRKD.git).

For reproducing our results, you can find the instructions in [segmentation/README.md](https://github.com/hunto/MasKD/blob/main/segmentation/README.md).

**Comment by cape-zck** [comment]
> 
That's right, thank you for your answer.

**Comment by cape-zck** [comment]
> Hi @cape-zck ,
> 
> Our experiments on semantic segmentation were not conducted on MMRazor, as we need to keep the training strategies and settings the same as previous works. Our code is based on [CIRKD](https://github.com/winycg/CIRKD.git).
> 
> For reproducing our results, you can find the instructions in [segmentation/README.md](https://github.com/hunto/MasKD/blob/main/segmentation/README.md).

That's right, thank you for your answer!
